services:
  - type: web
    name: water-system-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: MONGO_URI

pip install -r requirements.txt
        value: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/?retryWrites=true&w=majority
